### ISSUE TITLE
Companion App for SN

### ISSUE THREAD

**Issue by RaynorUE** [RaynorUE/snich#128]
## General Ideas
 
- Ability to store to SN things like "Table Config / Local Preferences"
  - This way they can have a centralized location to store table config, and anytime we "initialize the plugin" and/or load the table config, we look to their SN environment first..
   -  What if multiple SN Environments? Well maybe we have a global default config that's part of the app, and then we load in "instance unique" table configurations (something i've been meaning to add anyway..?) that overlay ontop of the default app configured ones. 
   - Could also add an option to "save global table configurations" to an instance of their choosing, and then add a "Load global table config" from an instance of their choosing (that is currently in workspace)

**Comment by macmorning** [comment]
Hi,
Maybe look into what is done by this extension?
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

Could be a future feature of VS Code also:
https://github.com/Microsoft/vscode/issues/2743

Becareful with how you sync passwords too.

Oh and thanks for Snich :)

**Comment by RaynorUE** [comment]
This is effectively done in the pre-release version 1.5.x , where we use the sys_user_preference table to store the users custom table configurations. 

Also, regarding comment about passwords, ii'm currently using my own implementation that encrypts any passwords / client secrets (oauth) using your PC's unique identifier as the encryption vector (not the greatest, but also not plain text, and requires attacker to gain access to your PC). 

I recently found out VSCode extensions have access to a VSCode built encryption provider (that they use for their own stuff) that i will be switching to here soon!
