### ISSUE TITLE
Test Connection failed. Uknown Error. View logs for detail.

### ISSUE THREAD

**Issue by hrax** [RaynorUE/snich#205]
**Describe the bug**
Testing connection to the instance. Test returns "Test Connection failed. Uknown Error. View logs for detail." Unfortunately there are no logs even when logging for SNICH is turned to debug level.

**Expected behavior**
Expect to see logs with the error in the Output section in the VSCode

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by RaynorUE** [comment]
Oh also, on the subject of Errors going to the Output view/Section ... working on a pretty huge re-write of SNICH in the "Canary" Branch  (There is also a Canary version on the marketplace that has a lot of updates over current live/prod version if you want to check it out).... which in this rewrite one of my plans is to use the Output section a bit more and "force show it" when errors/failures occur.

**Comment by hrax** [comment]
Hi Raynor,

Thank you for the pointing me to the right direction. I will use the logs to debug issues I am experiencing and if needed I will try to raise a new bug ticket.

I will try to have a look on the canary build as well, hopefully that may contain fixes for issues I am experiencing.
