### ISSUE TITLE
Instance Configuration Failed. Please attempt to setup new instance again. See log for details.

### ISSUE THREAD

**Issue by bzll** [RaynorUE/snich#220]
I'm trying to configure a new insntace using basic authentication (note: my instance is in San Diego version currently) but I don't know what is happening, I'm putting the correct password and user and then the screen bellow appears;
"Instance Configuration Failed. Please attempt to setup new instance again. See log for details."

**Comment by bzll** [comment]
I don't know if help, but I'm using node v18.7.0

**Comment by RaynorUE** [comment]
Hey there!

Sorry you're getting this error. Oddly I've used SNICH on countless number of instances and have not ran into this. Is it possible your computer or company uses a proxy and it's breaking the SSL Chain / exchange? Is this a Self-Hosted instance you are trying to connect to? Is it using a Custom URL? 

Couple of other things to try or provide more information to help me help you troubleshoot..

Can you try the S.N.I.C.H. Canary extension? (Oddly it's more up to date and stable that the current SNICH base... long story, sorry!)

If Canary is still failing, can you go to the VSCode settings, and look under the settings to S.N.I.C.H. and set the logging level to debug? This should print considerably more logs to maybe help understand what's failing.

**Comment by RaynorUE** [comment]
Oh also, regarding Node Versions, VSCode does not actually use your installed version of Node, but instead uses the version of Node that is bundled with the version of Electron VSCode is using for it's current version.

**Comment by francistwyman** [comment]
Thanks @RaynorUE, I was also having the same problem with SNICH when trying to sync records or configure tables (same error message).
But uninstalling and installing the canary version seems to have fixed it.
