### ISSUE TITLE
file naming issue - characters are being escaped to backslash

### ISSUE THREAD

**Issue by tylerstraub** [RaynorUE/snich#78]
SNITCH is currently transforming the colon `:` as a backslash `/` which upsets windows file naming.. and One Drive 

the character it’s escaping to `/` is a colon `:`

<img width="598" alt="Screen Shot 2019-05-28 at 9 07 08 AM" src="https://user-images.githubusercontent.com/4467134/58502248-0cd74980-813b-11e9-87d2-bbdb9ba6d231.png">

<img width="444" alt="Screen Shot 2019-05-28 at 9 02 41 AM" src="https://user-images.githubusercontent.com/4467134/58502250-0e087680-813b-11e9-8c0d-67ea5801f4f3.png">

**Comment by RaynorUE** [comment]
Just notating that we will do a pass on this, and try to detect if it's a windows system, and replace all "Non-Safe File/Folder characters" with an underscore.

**Comment by RaynorUE** [comment]
This has been resolved! Updated so that all file/folder names will be passed through a "fixForWindowsPath" method, that will replace all of the windows "Not allowed characters" with `_`
